import Head from 'next/head';
import useGameEngine from "@/game_engine/game_engine";
import {Character} from "@/components/characters/Character";
import {Pillar} from "@/components/obstacles/Pillar";
import {GameOver} from "@/components/game/GameOver";
import {Score} from "@/components/game/Score";

export default function Home() {
    const GAME_HEIGHT = 350;
    const DINO_HEIGHT = 50;
    const DINO_WIDTH = 50;
    const INITIAL_Y = 280;

    const { dinoRef, obstacles, obstacleRefs, isGameOver, points } = useGameEngine(INITIAL_Y, GAME_HEIGHT, DINO_HEIGHT, DINO_WIDTH);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div
                    style={{
                        position: 'relative',
                        width: '100%',
                        height: `${GAME_HEIGHT}px`,
                        overflow: 'hidden',
                        backgroundColor: '#ddd',
                    }}
                >
                    <Character width={DINO_WIDTH} height={DINO_HEIGHT} ref={dinoRef} />
                    {obstacles.map((obstacle) => (
                        <Pillar key={obstacle.id} ref={(el) => (obstacleRefs.current[obstacle.id] = el)} position={obstacle.position} />
                    ))}
                    {isGameOver && <GameOver />}
                    <Score points={points} />
                </div>
            </main>
        </>
    );
}

